#Ember-engine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ember-engine
  labels:
    app: ember-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ember-engine
  template:
    metadata:
      labels:
        app: ember-engine
    spec:
      serviceAccountName: 'ember-rbac'
      terminationGracePeriodSeconds: 30
      containers:
      - name: ember-engine
        image: gcr.io/ember-159719/ember-engine:latest
        ports:
        - containerPort: 12345
        resources:
          requests:
            memory: 15Gi
            cpu: 4
          limits:
            memory: 16Gi
            cpu: 4
        env:
          - name: EMBER_MONGO_URI
            value: "mongodb://root:rootPass@mongo-service/admin"
          - name: EMBER_MONGO_PORT
            value: "27017"
        readinessProbe:
          httpGet:
            path: /rest/hello
            scheme: HTTP
            port: 12345

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ember-rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ember-rbac-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ember-rbac
    namespace: default
  
